from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class OptionSet:
    values: tuple[str, ...]
    aliases: dict[str, str]

    def normalize(self, raw_value: str | None) -> str | None:
        if not raw_value:
            return raw_value
        cleaned = " ".join(raw_value.strip().split())
        if not cleaned:
            return cleaned
        alias_key = cleaned.upper()
        if alias_key in self.aliases:
            return self.aliases[alias_key]
        return cleaned


# ── Occupation (ownerOccupation / tenantOccupation) ─────────────────────────
# All 100+ portal labels — exact case as required by _select_by_label().
# Default pre-fill value: "SERVICE" (value 141).

OCCUPATIONS = OptionSet(
    values=(
        "ACADEMICIAN",
        "ACCOUNTANT",
        "AGENT",
        "AIR LINES STAFF",
        "AIRPORT STAFF",
        "ARCHITECT",
        "ARTISAN",
        "ARTIST",
        "ASST. SUPERVISOR",
        "BANK EMPLOYEE",
        "BARBER",
        "BLACK SMITH",
        "BROKER",
        "BUILDER",
        "BULLOCK CART DRIVER",
        "BUS CONDUCTOR",
        "BUSINESS",
        "CABLE OPERATORS",
        "CARPENTER",
        "CHAIRMAN",
        "CLEANER BUS",
        "CLEANER TRUCK",
        "COBBLER",
        "COMPANY EXECUTIVE",
        "COMPUTER PROFESSIONAL",
        "CONTRACTOR",
        "COOK",
        "COURIER",
        "CRAFTSMAN",
        "CREW",
        "Daily Wage Earner",
        "DEALER - ANTIQUE",
        "DEALER - SKIN & FUR",
        "DEFENCE PERSONNEL",
        "DOMESTIC HELPER",
        "DOMESTIC SERVANT",
        "DRAUGHTSMAN",
        "DRIVER",
        "DRIVER - BUS",
        "DRIVER - CAR",
        "DRIVER - CART",
        "DRIVER - TAXI",
        "DRIVER - TRUCK",
        "DRIVER-AUTORICKSHAW",
        "ELECTED REPRESENTATIVES",
        "ELECTRICIAN",
        "EMPLOYED IN PRIVATE FIRMS",
        "ENGINEERS",
        "EXPORTER",
        "FACTORY WORKER",
        "FARMER/CULTIVATOR",
        "FINANCIER",
        "FIREMAN",
        "FISHERMAN",
        "GARDNER",
        "GOLD SMITH",
        "GOVT. OFFICIAL GAZETTED",
        "GOVT. OFFICIAL NON-GAZETTED",
        "HAWKERS",
        "HELPER",
        "HOME-GUARD",
        "HOTEL EMPLOYEE",
        "HOUSE HELP - HIRED",
        "HOUSEWIFE",
        "IMPORTER",
        "INDUSTRIALIST",
        "JAIL STAFF",
        "JUDICIAL OFFICER",
        "JUGGLERS",
        "LABOURER",
        "LAUNDERER (DHOBI)",
        "LAW PRACTITIONER",
        "LINEMAN",
        "LITERARY PERSON",
        "MANAGER",
        "MASON",
        "MECHANIC",
        "MEDIA PERSON",
        "MEDICAL PRACTITIONER",
        "MERCENARY",
        "MILKMAN",
        "MINES EMPLOYEE",
        "MONEY LENDER",
        "NGOS EMPLOYEE",
        "NOT KNOWN",
        "NOT WORKING",
        "OTHERS",
        "PARA MEDICAL STAFF",
        "PEON",
        "PERSONNEL - ASSAM RIFLE",
        "PERSONNEL - BSF",
        "PERSONNEL - CISF",
        "PERSONNEL - CRPF",
        "PERSONNEL - ITBP",
        "PERSONNEL - NSG",
        "PERSONNEL - SSB",
        "PHOTOGRAPHER",
        "PILOT",
        "PLUMBER",
        "POLICE OFFICER",
        "POLITICIANS",
        "PORTER",
        "POSTAL STAFF",
        "Professional/Salaried Persons - Central/UT Govt Servants",
        "Professional/Salaried Persons - Other Statutory Body/ etc.",
        "Professional/Salaried Persons - Public Sector Undertaking",
        "Professional/Salaried Persons - State Govt Servants",
        "PROFESSOR",
        "RAILWAYS STAFF",
        "REAL ESTATE DEALER",
        "RELATIVE/FRIEND",
        "RELIGIOUS PERSON",
        "RETIRED EMPLOYEE",
        "RETIRED GOVT. EMPLOYEE",
        "RICKSHAW PULLER",
        "SALESMAN",
        "SANITARY WORKER",
        "SECURITY GUARD",
        "SERVICE",
        "SHOP EMPLOYEE",
        "SHOPKEEPER",
        "SOCIAL SERVICE",
        "SPORTS PERSON",
        "STUDENT",
        "SUPERVISOR",
        "SURVEYOR",
        "SWEEPER",
        "TAILOR",
        "TALLY CLERK",
        "TEACHER",
        "TECHNICIAN",
        "TELECOM STAFF",
        "TOURIST",
        "TRACTOR DRIVER",
        "TRADER",
        "TRAVELLING AS CO-PASSENGER",
        "UNEMPLOYED",
        "UTILITY SERIVCEMAN",
        "VENDOR",
        "VIDEO EXHIBITORS",
        "WATCHMEN",
        "WEAVER",
        "WELDER",
        "WORKING IN CPO/PARA MILITARY ORGANIZATION",
    ),
    aliases={
        "PRIVATE SERVICE": "SERVICE",
        "PVT SERVICE": "SERVICE",
        "PRIVATE JOB": "SERVICE",
        "SALARIED": "SERVICE",
        "GOVT SERVICE": "GOVT. OFFICIAL NON-GAZETTED",
        "GOVERNMENT SERVICE": "GOVT. OFFICIAL NON-GAZETTED",
        "SOFTWARE ENGINEER": "COMPUTER PROFESSIONAL",
        "IT PROFESSIONAL": "COMPUTER PROFESSIONAL",
        "DOCTOR": "MEDICAL PRACTITIONER",
        "ADVOCATE": "LAW PRACTITIONER",
        "CA": "ACCOUNTANT",
        "CHARTERED ACCOUNTANT": "ACCOUNTANT",
        "ENGINEER": "ENGINEERS",
        "NURSE": "PARA MEDICAL STAFF",
        "DAILY WAGE": "Daily Wage Earner",
    },
)

# Backward-compat alias used in existing extras_collection handler.
OWNER_OCCUPATIONS = OCCUPATIONS


# ── Tenancy purpose (tenancypurpose) ────────────────────────────────────────
# Portal stores exact case: "Residential" and "commercial".

TENANCY_PURPOSES = OptionSet(
    values=(
        "Residential",
        "commercial",
    ),
    aliases={
        "RESIDENTIAL": "Residential",
        "COMMERCIAL": "commercial",
        "BUSINESS": "commercial",
        "OFFICE": "commercial",
    },
)


# ── Address verification document type (tenantAddressDocuments) ─────────────
# Exact portal labels from live log capture.

ADDRESS_DOC_TYPES = OptionSet(
    values=(
        "Aadhar Card",
        "Any Other",
        "Arms License",
        "Driving License",
        "Electricity Bill",
        "Income Tax (PAN) Card",
        "Passport",
        "Ration Card",
        "Telephone Bill",
        "Voter Card",
    ),
    aliases={
        "AADHAAR": "Aadhar Card",
        "AADHAAR CARD": "Aadhar Card",
        "AADHAR": "Aadhar Card",
        "UID": "Aadhar Card",
        "PAN": "Income Tax (PAN) Card",
        "PAN CARD": "Income Tax (PAN) Card",
        "VOTER ID": "Voter Card",
        "VOTER CARD": "Voter Card",
        "DL": "Driving License",
        "DRIVING LICENSE": "Driving License",
        "DRIVING LICENCE": "Driving License",
        "PASSPORT": "Passport",
        "RATION CARD": "Ration Card",
        "ELECTRICITY BILL": "Electricity Bill",
        "TELEPHONE BILL": "Telephone Bill",
        "ARMS LICENSE": "Arms License",
        "ARMS LICENCE": "Arms License",
    },
)


# ── Countries (ownerCountry / tenantPermanentCountry) ──────────────────────
# Exact portal labels as captured from dropdowns.

COUNTRIES = OptionSet(
    values=(
        "INDIA",
        "ABU DHABI/DUBAI",
        "AFGHANISTAN",
        "AFRICA",
        "ALBANIA",
        "ALGERIA",
        "ANDORRA",
        "ANGOLA",
        "ARGENTINA",
        "ARMENIA",
        "AUSTRALIA",
        "AUSTRIA",
        "AZERBAIJAN",
        "BAHAMAS",
        "BAHRAIN",
        "BANGLADESH",
        "BARBADOS",
        "BELORUSSIA",
        "BENIN",
        "BELGIUM",
        "BERMUDA",
        "BHUTAN",
        "BOLIVIA",
        "BOSNIA - HERZEGOVINA",
        "BOTSWANA",
        "BRAZIL",
        "BRITISH HONDURAS",
        "BRUNEI",
        "BULGARIA",
        "BURKINA",
        "BURUNDI",
        "CAMBODIA",
        "CAMEROON",
        "CANADA",
        "CAPE VERDE",
        "CENTRAL AFRICAN REPUBLIC",
        "CHAD",
        "CHILE",
        "CHINA",
        "COLOMBIA",
        "COMOROS",
        "CONGO",
        "COSTARICA",
        "CROATIA",
        "CUBA",
        "CYPRUS",
        "CZECH REPUBLIC",
        "DENMARK",
        "DJIBOUTI",
        "DOMINICA",
        "DOMINICAN REPUBLIC",
        "ECUADOR",
        "EGYPT",
        "ELSALVADOR",
        "EQUATORIAL GUINEA",
        "ERITREA",
        "ESTONIA",
        "ETHIOPIA",
        "FALKLAND ISLANDS",
        "FEDERATION OF NIGERIA",
        "FIJI",
        "FINLAND",
        "FRANCE",
        "FRENCH POLYNESIA",
        "GABON",
        "GAMBIA",
        "GEORGIA",
        "GERMANY",
        "GHANA",
        "GREECE",
        "GRENADA",
        "GUATEMALA",
        "GUINEA",
        "GUINEA BISSAU",
        "GUYANA",
        "HAITI",
        "HONDURAS",
        "HONGKONG",
        "HUNGARY",
        "ICELAND",
        "INDONESIA",
        "IRAN",
        "IRAQ",
        "IRELAND (EIRE)",
        "ISRAEL",
        "ITALY",
        "IVORY COAST",
        "JAMAICA",
        "JAPAN",
        "JORDAN",
        "KAZAKHISTAN",
        "KENYA",
        "KIRGIZIA",
        "KIRIBATI",
        "NORTH KOREA",
        "SOUTH KOREA",
        "KUWAIT",
        "LAOS",
        "LATVIA",
        "LEBANON",
        "LESOTHO",
        "LIBERIA",
        "LIBYA",
        "LIECHTENSTEIN",
        "LITHUNIA",
        "LUXEMBOURG",
        "MADAGASCAR",
        "MALAWI",
        "MALAYA",
        "MALAYSIA",
        "MALDIVES",
        "MALI",
        "MALTA",
        "MAURITANIA",
        "MAURITIUS",
        "MEXICO",
        "MOLDAVIA",
        "MONACO",
        "MONGOLIA",
        "MOROCCO",
        "MOZAMBIQUE",
        "MUSCAT",
        "MYANMAR",
        "NAMIBIA",
        "NEPAL",
        "NETHERLANDS",
        "NETHERLANDS ANTILLES",
        "NEW ZEALAND",
        "NICARAGUA",
        "NIGER",
        "NIGERIA",
        "NORWAY",
        "OMAN",
        "PAKISTAN",
        "PANAMA",
        "PAPUA NEW GUINEA",
        "PARAGUAY",
        "PERU",
        "PHILIPPINES",
        "POLAND",
        "PORTUGAL",
        "PUERTO RICO",
        "QATAR",
        "ROMANIA",
        "RUSSIAN FEDERATION",
        "RWANDA",
        "SAN MARINO",
        "SAO TOME AND PRINCIPE",
        "SAUDI ARABIA",
        "SENEGAL",
        "SEYCHELLES",
        "SIERRA LEONE",
        "SINGAPORE",
        "SLOVAKIA",
        "SLOVENIA",
        "SOLOMAN ISLANDS",
        "SOMALIA",
        "SOUTH AFRICA",
        "SPAIN",
        "SRI LANKA",
        "ST KITTS - NEVIS",
        "ST LUCIA",
        "ST VINCENT",
        "SUDAN",
        "SURINAM",
        "SWAZILAND",
        "SWEDEN",
        "SWITZERLAND",
        "SYRIA",
        "TAIWAN",
        "TAJIKISTAN",
        "TANZANIA",
        "TASMANIA",
        "THAILAND",
        "TIBET",
        "TOGO",
        "TONGA",
        "TRINIDAD & TOBAGO",
        "TUNISIA",
        "TURKEMANISTAN",
        "TURKEY",
        "TUVALLI",
        "UGANDA",
        "UKRAINE",
        "UNITED ARAB EMIRATES (UAE)",
        "UNITED KINGDOM (UK)",
        "UNITED STATES OF AMERICA (USA)",
        "UPPER VALTA",
        "URUGUAY",
        "UZBEKISTAN",
        "VANUATU",
        "VATICAN",
        "VENEZUELA",
        "VIETNAM",
        "WALLIS & FUTUNA ISLANDS",
        "WEST INDIES",
        "WESTERN AUSTRALIA",
        "WESTERN SAMOA",
        "YEMAN",
        "YUGOSLAVIA",
        "YUKON",
        "ZAIRE",
        "ZAMBIA",
        "ZIMBABWE",
        "BELARUS",
        "BELIZE",
        "BRITAIN",
        "ENGLAND",
        "MACEDONIA",
        "MOLDOVA",
        "MONTENEGRO",
        "SCOTLAND",
        "SERBIA",
        "WALES",
        "UNKNOWN",
    ),
    aliases={},
)


# ── Indian states (tenantPermanentState) ────────────────────────────────────
# Values are UPPERCASE to match STATE_VALUES keys in form_filler.py.
# Aliases map common OCR abbreviations and misspellings to canonical values.

STATES = OptionSet(
    values=(
        "ANDAMAN & NICOBAR",
        "ANDHRA PRADESH",
        "ARUNACHAL PRADESH",
        "ASSAM",
        "BIHAR",
        "CHANDIGARH",
        "CHHATTISGARH",
        "DADRA & NAGAR HAVELI",
        "DAMAN & DIU",
        "DELHI",
        "GOA",
        "GUJARAT",
        "HARYANA",
        "HIMACHAL PRADESH",
        "JAMMU & KASHMIR",
        "JHARKHAND",
        "KARNATAKA",
        "KERALA",
        "LADAKH",
        "LAKSHADWEEP",
        "MADHYA PRADESH",
        "MAHARASHTRA",
        "MANIPUR",
        "MEGHALAYA",
        "MIZORAM",
        "NAGALAND",
        "ODISHA",
        "PUDUCHERRY",
        "PUNJAB",
        "RAJASTHAN",
        "SIKKIM",
        "TAMIL NADU",
        "TELANGANA",
        "TRIPURA",
        "UTTAR PRADESH",
        "UTTARAKHAND",
        "WEST BENGAL",
    ),
    aliases={
        "UP": "UTTAR PRADESH",
        "U.P.": "UTTAR PRADESH",
        "UK": "UTTARAKHAND",
        "UTTARAKHAND": "UTTARAKHAND",
        "UTTARANCHAL": "UTTARAKHAND",
        "UTTRAKHAND": "UTTARAKHAND",
        "MP": "MADHYA PRADESH",
        "M.P.": "MADHYA PRADESH",
        "HP": "HIMACHAL PRADESH",
        "H.P.": "HIMACHAL PRADESH",
        "HIMACHAL": "HIMACHAL PRADESH",
        "J&K": "JAMMU & KASHMIR",
        "J & K": "JAMMU & KASHMIR",
        "AP": "ANDHRA PRADESH",
        "A.P.": "ANDHRA PRADESH",
        "TN": "TAMIL NADU",
        "T.N.": "TAMIL NADU",
        "TAMILNADU": "TAMIL NADU",
        "TAMIL NAIDU": "TAMIL NADU",
        "WB": "WEST BENGAL",
        "W.B.": "WEST BENGAL",
        "CG": "CHHATTISGARH",
        "JH": "JHARKHAND",
        "PB": "PUNJAB",
        "KA": "KARNATAKA",
        "KL": "KERALA",
        "GJ": "GUJARAT",
        "MH": "MAHARASHTRA",
        "RJ": "RAJASTHAN",
        "HR": "HARYANA",
        "AS": "ASSAM",
        "BR": "BIHAR",
        "OR": "ODISHA",
        "ORISSA": "ODISHA",
        "NEW DELHI": "DELHI",
        "NCT": "DELHI",
        "NCT OF DELHI": "DELHI",
        "TELENGANA": "TELANGANA",
        "PONDICHERRY": "PUDUCHERRY",
        "PONDI": "PUDUCHERRY",
    },
)


# ── Relation type (ownerRelationType / tenantRelationType) ───────────────────
# Exact portal labels (value: Father=5, Guardian=7, Husband=8, Mother=6, Wife=9).

RELATION_TYPES = OptionSet(
    values=(
        "Father",
        "Guardian",
        "Husband",
        "Mother",
        "Wife",
    ),
    aliases={
        "F/O": "Father",
        "S/O": "Father",
        "D/O": "Father",
        "W/O": "Husband",
        "H/O": "Wife",
        "M/O": "Mother",
        "C/O": "Guardian",
        "SON OF": "Father",
        "DAUGHTER OF": "Father",
        "WIFE OF": "Husband",
        "HUSBAND OF": "Wife",
        "MOTHER OF": "Mother",
    },
)
