#!/usr/bin/env python3
"""
Scrape district → police-station lists from the Delhi Police tenant portal
for each Indian state (tenant permanent address dropdowns).

Requires PORTAL_USERNAME / PORTAL_PASSWORD in .env (see shared.config).

Usage:
  python scripts/scrape_police_stations.py --bootstrap
      Write an empty data/national_police_stations.json (schema only).

  python scripts/scrape_police_stations.py --scrape [--limit N] [--headed]
      Log in, open the tenant form, iterate states, write national JSON.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import logging
import sys
from pathlib import Path

LOGGER = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = REPO_ROOT / "data"
DELHI_FILE = DATA_DIR / "delhi_police_stations.json"
NATIONAL_FILE = DATA_DIR / "national_police_stations.json"


def bootstrap(output: Path) -> None:
    payload = {
        "_meta": {
            "note": "Generated by scrape_police_stations.py --bootstrap",
            "schema": "by_state -> STATE_NAME -> { DISTRICT_NAME: [ police_station_name, ... ] }",
        },
        "by_state": {},
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    LOGGER.info("Wrote %s", output)


async def _option_labels(page, select_name: str) -> list[str]:
    return await page.eval_on_selector_all(
        f'[name="{select_name}"] option',
        """els => els.map(e => e.textContent.trim()).filter(t => {
            if (!t) return false;
            const u = t.toUpperCase();
            const collapsed = u.replace(/-/g, "").trim();
            return collapsed !== "" && !collapsed.startsWith("SELECT");
        })""",
    )


async def _js_select_by_value(page, field_name: str, value: str) -> None:
    """Set a <select> by option value and fire the change event the portal listens to."""
    await page.evaluate(
        """([name, val]) => {
            const el = document.querySelector('[name="' + name + '"]');
            if (!el) throw new Error('Element not found: ' + name);
            el.value = val;
            el.dispatchEvent(new Event('change', { bubbles: true }));
        }""",
        [field_name, value],
    )


async def _js_select_by_label(page, field_name: str, label: str) -> None:
    """Set a <select> by visible label text and fire the change event."""
    await page.evaluate(
        """([name, lbl]) => {
            const el = document.querySelector('[name="' + name + '"]');
            if (!el) throw new Error('Element not found: ' + name);
            const opt = Array.from(el.options).find(o => o.textContent.trim() === lbl);
            if (!opt) {
                const avail = Array.from(el.options).map(o => o.textContent.trim()).join(', ');
                throw new Error('Label "' + lbl + '" not in ' + name + '. Available: ' + avail);
            }
            el.value = opt.value;
            el.dispatchEvent(new Event('change', { bubbles: true }));
        }""",
        [field_name, label],
    )


async def scrape(output: Path, *, limit: int | None, headed: bool) -> None:
    # Import after repo root is on path
    sys.path.insert(0, str(REPO_ROOT))
    from playwright.async_api import async_playwright

    from features.submission.portal_session import PortalSession
    from shared.config import load_settings

    settings = load_settings()
    if not settings.portal_username or not settings.portal_password:
        raise SystemExit("PORTAL_USERNAME and PORTAL_PASSWORD must be set in .env")

    states_map: dict[str, str] = json.loads(DELHI_FILE.read_text(encoding="utf-8"))[
        "states"
    ]
    items = sorted(states_map.items(), key=lambda x: x[0])
    if limit is not None:
        items = items[:limit]

    by_state: dict[str, dict[str, list[str]]] = {}

    async with async_playwright() as p:
        session = PortalSession(
            settings.portal_username,
            settings.portal_password,
            p,
            headless=not headed,
            logger=LOGGER,
        )
        page = await session.open()
        try:
            await page.click("text=Tenant Information")
            await page.wait_for_selector(
                '[name="tenantFirstName"]', state="visible", timeout=120000
            )
            await page.evaluate(
                '() => document.querySelector(\'[href="javascript:TabView.switchTab(1,1);"]\')?.click()'
            )
            await page.wait_for_selector(
                "text=Tenanted Premises Address", state="visible", timeout=120000
            )
            await page.click("text=Permanent Address")
            await page.wait_for_selector(
                '[name="tenantPermanentState"]', state="visible", timeout=120000
            )

            for state_name, state_val in items:
                key = state_name.strip().upper()
                LOGGER.info("State: %s", key)
                try:
                    async with page.expect_response(
                        lambda r: "getdistricts" in r.url.lower(),
                        timeout=20000,
                    ):
                        await _js_select_by_value(
                            page, "tenantPermanentState", str(state_val)
                        )
                    await page.wait_for_function(
                        """() => {
                        const s = document.querySelector('[name="tenantPermanentDistrict"]');
                        return s && s.options && s.options.length > 1;
                        }""",
                        timeout=10000,
                    )
                except Exception as exc:
                    LOGGER.warning("Skip state %s (districts did not load): %s", key, exc)
                    continue

                district_labels = await _option_labels(page, "tenantPermanentDistrict")
                by_state[key] = {}
                for d_label in district_labels:
                    if not d_label:
                        continue
                    d_key = d_label.strip().upper()
                    try:
                        async with page.expect_response(
                            lambda r: "getpolicestations" in r.url.lower(),
                            timeout=15000,
                        ):
                            await _js_select_by_label(
                                page, "tenantPermanentDistrict", d_label
                            )
                        await page.wait_for_function(
                            """() => {
                            const s = document.querySelector('[name="tenantPermanentPoliceStation"]');
                            return s && s.options && s.options.length > 1;
                            }""",
                            timeout=10000,
                        )
                    except Exception as exc:
                        LOGGER.debug("District %s / %s: %s", key, d_label, exc)
                        by_state[key][d_key] = []
                        continue
                    stations = await _option_labels(page, "tenantPermanentPoliceStation")
                    by_state[key][d_key] = [s.strip() for s in stations if s.strip()]

        finally:
            await session.close()

    payload = {
        "_meta": {
            "source": "scripts/scrape_police_stations.py --scrape",
            "states_scraped": len(by_state),
        },
        "by_state": by_state,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    LOGGER.info("Wrote %s (%d states)", output, len(by_state))


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description="National police station data scraper")
    parser.add_argument(
        "--bootstrap",
        action="store_true",
        help="Write empty national_police_stations.json",
    )
    parser.add_argument(
        "--scrape",
        action="store_true",
        help="Scrape portal (requires credentials)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=NATIONAL_FILE,
        help="Output JSON path",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Max number of states to scrape (for testing)",
    )
    parser.add_argument(
        "--headed",
        action="store_true",
        help="Show browser window during scrape",
    )
    args = parser.parse_args()
    if args.bootstrap:
        bootstrap(args.output)
        return
    if args.scrape:
        asyncio.run(scrape(args.output, limit=args.limit, headed=args.headed))
        return
    parser.print_help()
    raise SystemExit(1)


if __name__ == "__main__":
    main()
